### ISSUE TITLE
Download resume not implemented

### ISSUE THREAD

**Issue by mrnninster** [mrnninster/my_portfolio_blog#3]
In the resume page inself, there are two instances where youshould be able to download the resume, but the haven't been implemented partly because I am unsure as to what I want to do. The easiest way is to use the javascript print function on the page and save it as a pdf, but I also considering if it would be better to allow upload of resume files that can then be downloaded

PS. I don't want to do both.

**Comment by unkwnownGriot** [comment]
hey how are you doing . I have a problem with your project, an import problem, but I have already installed the different dependencies with pip. I don't understand or it is because I have created a virtual environment. 
![2023-02-15 13_23_14-__init__ py - my_portfolio_blog - Visual Studio Code](https://user-images.githubusercontent.com/83823820/219039915-6501af8a-0e93-4e71-a996-c1d67053e91d.png)

**Comment by mrnninster** [comment]
Hi @unkwnownGriot can you paste the error you are getting here, I dont expect that a virtual environment would give an error because I am doing the same

**Comment by unkwnownGriot** [comment]
i'm facing import error for module such as flask and it's extension and that is strange because when i do pip freeze i can see them. Let me try something

**Comment by unkwnownGriot** [comment]
solve it. Don't know but my virtual environment was not activate strange

**Comment by mrnninster** [comment]
Okay thats fine, just in case you'd have some other problems with the project, please create a new issue, this problem wasn't related to the reason this issue was created for.

**Comment by mrnninster** [comment]
I will now be closing this issue since i have implemented it in the current commit.
